version: '3'
services:
  postgres:
    container_name: personal-finance-db
    image: docker.io/library/postgres:14
    platform: linux/arm64
    environment:
      POSTGRES_DB: personal_finance
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - personal-finance-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    restart: always
    # Optimalisert for M4-prosessor
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d personal_finance"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  personal-finance-data:
    driver: local